"""add_user_daily_activity

Revision ID: 7417ea2de401
Revises: c85557413a32
Create Date: 2026-09-22 12:12:31.595196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7417ea2de401'
down_revision: Union[str, Sequence[str], None] = 'c85557413a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_activity',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('reviews_completed', sa.Integer(), nullable=True),
    sa.Column('bookmarks_added', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_daily_activity')
    # ### end Alembic commands ###
