"""remove_snapshots

Revision ID: c85557413a32
Revises: b5949707827c
Create Date: 2026-09-22 12:09:23.252471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85557413a32'
down_revision: Union[str, Sequence[str], None] = 'b5949707827c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_snapshots_problem_id'), table_name='code_snapshots')
    op.drop_table('code_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_snapshots',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('problem_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.CHAR(length=32), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.Column('code_text', sa.VARCHAR(), nullable=True),
    sa.Column('code_hash', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index(op.f('ix_code_snapshots_problem_id'), 'code_snapshots', ['problem_id'], unique=False)
    # ### end Alembic commands ###
